#!/usr/bin/env bash

set -e

. /srv/ganeti/extstorage/zfs/defaults.sh

if ! test -e "/dev/zvol/$EXTP_ZFS/$VOL_NAME"; then
  echo "/dev/zvol/$EXTP_ZFS/$VOL_NAME does not exist on $(hostname)"
  exit 1
fi

# Return path to blockdevice
echo -n "/dev/zvol/$EXTP_ZFS/$VOL_NAME"
