#!/usr/bin/env bash

set -e

. /usr/share/ganeti/extstorage/zfs/defaults.sh

zfs set ganeti:metadata="${VOL_METADATA}" "${EXTP_ZFS}/${VOL_NAME}"

IFS="+" read -r tag value <<< "${VOL_METADATA}"
zfs set ganeti:"${tag}"="${value}" "${EXTP_ZFS}/${VOL_NAME}"
